# Generated by Django 5.2.4 on 2025-07-27 08:59

from django.db import migrations, models


class Migration(migrations.Migration):
  initial = True

  dependencies = []

  operations = [
    migrations.CreateModel(
      name="ShortenedURL",
      fields=[
        (
          "id",
          models.BigAutoField(
            auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
          ),
        ),
        ("url", models.URLField(max_length=2000)),
        ("short_url", models.CharField(blank=True, max_length=10, unique=True)),
        ("created_at", models.DateTimeField(auto_now_add=True)),
        ("click_count", models.PositiveIntegerField(default=0)),
      ],
    ),
  ]
